### ISSUE TITLE
Offsite Backup of files on Hertz

### ISSUE THREAD

**Issue by kusalananda** [NBISweden/swefreq#155]
The files relating to the Swefreq-NG on the hosting Hertz server (including user database dumps and the containers themselves) needs to be properly backed up.
I will contact Stefan about this.

**Comment by jhagberg** [comment]
Will talk to @nmb and @stiobhan  what will be the best of-site backup solution for the whole Hertz system

**Comment by jhagberg** [comment]
Update decision to use tsm.uu.se 
@stiobhan Can you order and install ? I can assist with the ordering.

**Comment by nicjar** [comment]
@jhagberg status for this?

**Comment by viklund** [comment]
Now the backup to tsm is running as part of the SweFreq `backup.sh` script.
