### ISSUE TITLE
Set up nginx proxy

### ISSUE THREAD

**Issue by viklund** [NBISweden/swefreq#23]

**Comment by jhagberg** [comment]
Okey I have set up a proxy. 
Questions. Tornado is running with ssl. I do not know what is best practice but it do not really need to be encrypted communication between localhost and nginx proxy. And it can bork things when ssl certificates has to renew. So my take is to running the tornardo server without SSL. 

Also it might be a good Idea to run several backend python processes to be able to cope with more traffic. 
nginx proxy can round robin this very well. But can we run several instances of tornado?

For example look at this setup
http://stackoverflow.com/questions/14749655/setting-up-a-tornado-web-service-in-production-with-nginx-reverse-proxy

Can we get @MatsDahlberg comments?

**Comment by viklund** [comment]
Yes we need to do something about performance, I've added issue #29 for  that.

**Comment by jhagberg** [comment]
all done
