### ISSUE TITLE
[exac] Fix links in menu

### ISSUE THREAD

**Issue by nicjar** [NBISweden/swefreq#25]
* About Exac - 
* Download
  * Link to https://swefreq.nbis.se/#/downloadData/
* Terms
  * Update text
* Contact
  * Add contact mail aliases
* FAQ
  * Hide or update text

**Comment by viklund** [comment]
Fixed: _Download_, _Terms_, _Contact_ and _FAQ_. Please check.

I also forgot what to put in _About Exac_, the same text as on the swefreq main website?

**Comment by viklund** [comment]
_About exac_ keep only the "to cite the browser..." paragraph.

**Comment by viklund** [comment]
_Terms_ in exac site: remove sentence 2 and 3:

"The variant frequency files, or modified versions of the files, may not be redistributed to other users. Each user is required to register in the system and download his/her own copy from this central site and it responsible that this information is not distributed to others. "

**Comment by viklund** [comment]
_Contact_ email is: `swefreq@scilifelab.se` for technical issues `swegen@scilifelab.se` for the dataset.

**Comment by nicjar** [comment]
Till contact 
swegen@scilifelab.se - for questions, comments, errors, etc., regarding the SweGen cohort dataset.

**Comment by kusalananda** [comment]
Have fixed the About page. Have fixed the page header.
See pull request #46.

**Comment by nicjar** [comment]
Föreslår att ändra _About SweFreq_ till _About SweGen ExAC_
