### ISSUE TITLE
Set up development and switch-over production servers

### ISSUE THREAD

**Issue by nicjar** [NBISweden/swefreq#26]

**Comment by kusalananda** [comment]
Three alternatives, and a thought:

1. Allowing full testing (both of website and of database) before deployment:
 - Completely clone currently live container.
 - Update and test the new container.
 - Switch the two the the new one is ready.
 - Delete old container.
 - Repeat.

2. Allowing testing of database before deployment:
 - Set up two separate database containers.
 - Load ExAC-database into one.
 - Point live site there.
 - Follow above scheme for database container only.

3. Combine 2 & 3 above.

4. For multiple datasets, use multiple instances of ExAC-browser installations.

**Comment by viklund** [comment]
This is the same as issue 140
