### ISSUE TITLE
Terms & conditions-text till nedladdningssidan

### ISSUE THREAD

**Issue by nicjar** [NBISweden/swefreq#32]
**Update: Don't use this! See below**

---

**Terms of use**

You are allowed to freely search the data available at this site, and files with genome-wide variant frequencies are available for academic use upon registration. The variant frequency files, or modified versions of the files, may not be redistributed to other users. Each user is required to register in the system and download his/her own copy from this central site and it responsible that this information is not distributed to others. We encourage the use and publication of frequency data for specific targeted sets of variants (for instance, assessing a set of candidate causal variants observed in a collection of rare disease patients). However, you are not allowed to publish global (genome-wide) analyses of the complete data set or large gene sets, until after the first SweGen paper, describing the resource, has been published in a peer-reviewed journal (estimated to be in early 2017).

**Disclaimer**

This database is based on individuals from population-based cross-sectional studies. No phenotype information has been used as inclusion criteria in the database. Individuals with common diseases occur at the general population prevalence of the disease. As a consequence, genetic variants contributing to disease risk occur in the database at the general population frequency. There is no explicit or implicit guarantee that the genetic variants in the database do not contribute to risk of disease. 

**Citation in publications**

Any use of SweGen data should be cited by [our preprint on bioRxiv](http://somewhere.some.place).

**Comment by nicjar** [comment]
_Nya bud:_

**Terms of use**

All data in the SweGen dataset are human allele frequencies estimated from aggregates across large sample groups, rendering contributing individuals non-identifiable. The method used for estimating the frequencies is described in the corresponding publication. Data is versioned and frequencies in different data versions may be different. No individual level genetic data is contained in this dataset. We encourage the use and publication of frequency data for specific targeted sets of variants (for instance, assessing a set of candidate causal variants observed in a collection of rare disease patients).

By accessing the data you agree to the following terms and conditions, irrespective of the method used to retrieve the data (for example vcf file download or variant query through Beacon or other methods):

1. You are allowed to freely search the data at the SweFreq website, and download any files containing allele frequency data made available on this site after registration.
2. The data may not be used to attempt to identify any individual in this or other studies.
3. No global analysis of the data may be published before the SweGen project’s own upcoming publication, estimated early 2017. A notice will appear on https://swefreq.nbis.se stating when new global analyses may be published.
4. Any published study that includes processing of the data shall include the data version used, acknowledge the original study with the sentence “The SweGen allele frequency data was generated by Science for Life Laboratory”, and cite the following publication: _SweGen: A whole-genome map of genetic variability in a cross-section of the Swedish population. Ameur et al., bioRxiv 081505; (doi:10.1101/081505)_
5. The data may be redistributed in original or modified form, but must always be distributed together with the file “terms_of_use.txt” that is stored together with the data and available here [https://swefreq.nbis.se/#/downloadData/], and any redistributed data derived from the SweGen data set must follow those terms and conditions.

**Disclaimer**

This dataset is based on individuals from population-based cross-sectional studies. No phenotype information has been used as inclusion criteria in the dataset. Individuals with common diseases occur at the general population prevalence of the disease. As a consequence, genetic variants contributing to disease risk occur in the dataset at the general population frequency. There is no explicit or implicit guarantee that the genetic variants in the dataset do not contribute to risk of disease.

**Citation in publications**

Any use of SweGen data should be cited by our preprint on bioRxiv [http://biorxiv.org/content/early/2016/10/17/081505]

**Comment by kusalananda** [comment]
Allt fixat.
