### ISSUE TITLE
Write `terms of service` och `policy statement`

### ISSUE THREAD

**Issue by nicjar** [NBISweden/swefreq#331]
Needed for ELIXIR AAI

_Drafts:_
* [Privacy policy statement](https://github.com/NBISweden/swefreq/wiki/Privacy-Policy-statement)
* [Terms of Service](https://github.com/NBISweden/swefreq/wiki/Terms-of-Service-statement)

**Comment by viklund** [comment]
Policy statement is probably a _privacy policy_

**Comment by nicjar** [comment]
[Privacy policy statement](https://github.com/NBISweden/swefreq/wiki/Privacy-Policy-statement)

**Comment by nicjar** [comment]
Make urls
