### ISSUE TITLE
Investigate possibility to get Swedish ExAC data into SweFreq

### ISSUE THREAD

**Issue by nicjar** [NBISweden/swefreq#352]
- [x] Andreas komma i kontakt med en person med data.
- [ ] Metadata format (för swefreq).
- [ ] Beskrivning av hur browser datasetet ska se ut.

**Comment by viklund** [comment]
Johan Rung: "Grönt ljus från Patrick Sullivan att preparera frekvenser från de 14000 svenska ExAC-exomen som dataset #2. Vi behöver ta fram en SOP för att preparera de filer och metadata som behövs. Hur mycket finns redan och hur mycket behöver vi från Adam och co?"

**Comment by viklund** [comment]
- [ ] Andreas komma i kontakt med en person med data.
- [ ] Metadata format (för swefreq).
