### ISSUE TITLE
PROC Gene don't load in the browser for the swegen dataset

### ISSUE THREAD

**Issue by viklund** [NBISweden/swefreq#404]
There's no coverage there but there seems like there are SNPs:

PROC gene page:
https://swegen-exac.nbis.se/gene/ENSG00000115718

PROC Gene region:
https://swegen-exac.nbis.se/region/2-128176003-128186822

**Comment by viklund** [comment]
This gene seems to have the same issue:

Gene: https://swegen-exac.nbis.se/gene/ENSG00000221957
Region: https://swegen-exac.nbis.se/region/19-55344131-55360024

**Comment by jessada** [comment]
It seems like all the genes within 19:54673292-58879458 also have this issue

Here is the list of the genes in the region:
TMC4
LILRB5
LILRA3
LENG9
LAIR2
LILRA1
KIR2DL3
KIR2DL1
KIR2DL4
NCR1
GP6
RDH13
COX6B2
SSC5D
NLRP13
ZNF444
ZNF471
ZNF835
ZIM3
DUXA
ZNF749
ZNF772
ZNF211
ZNF551
ZNF154
ZNF814
ZNF417
ZNF544
ZNF837

The region might be bigger. Those are the genes I've checked

**Comment by viklund** [comment]
We fixed this a while ago. The problem was that there is no coverage in this region for some reason. If there should be coverage here we need updated coverage vcf files.
