### ISSUE TITLE
Update tar-file

### ISSUE THREAD

**Issue by viklund** [NBISweden/swefreq#44]
swegen_20161019.tar

including folder name.

**Comment by kusalananda** [comment]
The file is in place, with the correct name and folder structure. It's 4.5 Gb, if we want to mention that anywhere. We could also mention its MD5 digest, maybe (see below).  The link the it now needs updating.

```
$ pwd
/opt/swefreq/tornado/static

$ tar tf swegen-20161019.tar
swegen-20161019/
swegen-20161019/anon-SweGen_STR_NSPHS_1000samples_indel_freq_hg19.vcf.gz
swegen-20161019/anon-SweGen_STR_NSPHS_1000samples_snp_freq_hg19.vcf.gz
swegen-20161019/anon-SweGen_STR_NSPHS_1000samples_indel_freq_hg19.vcf.gz.tbi
swegen-20161019/anon-SweGen_STR_NSPHS_1000samples_snp_freq_hg19.vcf.gz.tbi

$ md5sum swegen-20161019.tar
d5c3c74269f79dc590b91169d1c2cc05  swegen-20161019.tar
```

**Comment by nicjar** [comment]
Vi ska ha en terms_of_use.txt fil med i tar-arkivet.
[terms_of_use-release_20161019.txt](https://github.com/NBISweden/swefreq/files/536258/terms_of_use-release_20161019.txt)

**Comment by kusalananda** [comment]
All done.
