### ISSUE TITLE
Standard output log not flushed (partial output in logfile)

### ISSUE THREAD

**Issue by kusalananda** [NBISweden/swefreq#462]
The log of the browser's standard output contains partial output.  This is due to the output not being properly flushed when writing.

This affects `/var/log/flask/swefreq-browser-stdout.log` in the web containers.

The standard error log does not have this issue since output to the standard error stream is not buffered by default.

I will fix this.

**Comment by viklund** [comment]
Closing this since it is not relevant for our current browser setup.
