### ISSUE TITLE
use the new beacon from the web page

### ISSUE THREAD

**Issue by talavis** [NBISweden/swefreq#539]
### Description
The beacon interface on the web interface should use the new beacon instead of the minimal old one.

### Proposed solution
Updated the requests and interface to match the new beacon, as defined by the API specification at https://github.com/ga4gh-beacon/specification/blob/develop/beacon.yaml. A reference beacon submission form is available at https://beacon-ui-beacon.rahtiapp.fi/.

### Definition of Done
It is possible to perform queries to the new beacon from the SweFreq web interface.

**Comment by viklund** [comment]
Fixed in the new release.
