### ISSUE TITLE
Incorrect SweGen download link

### ISSUE THREAD

**Issue by viklund** [NBISweden/swefreq#605]
On this page, https://swefreq.nbis.se/dataset/SweGen/version/20180409/terms, the text `here` under 4. links to https://swefreq.nbis.se/#/downloadData/. It should probably just link to the "Dataset Access" tab.

It probably needs to be updated in the database (possibly for all swegen versions).

**Comment by talavis** [comment]
Links are updated. I believe the text should also be altered a bit, but at least the links are accurate now.
