### ISSUE TITLE
Swefreq browser not returning coverage for swegen dataset

### ISSUE THREAD

**Issue by viklund** [NBISweden/swefreq#635]
# Description

The genome browser of swefreq does not show anything for the SweGen dataset but it works for ACpop. Unclear how long this behaviour has been there. Before the SweGen dataset worked.

# How to replicate:

Go to https://swefreq.nbis.se and click the graphical browser on either dataset, then choose the PCSK9 gene example. In the ACPOP dataset we get a list of variants and sequencing coverage, for SweGen there's a sole 404 returned.

 * [SweGen PCSK9](https://swefreq.nbis.se/dataset/SweGen/browser/gene/ENSG00000169174)
 * [ACPop PCSK9](https://swefreq.nbis.se/dataset/ACpop/browser/gene/ENSG00000169174)

# Extra notes

To debug and figure out what is happening, one will probably need to do things in the production instance to fix things. Please contact Johan or Andreas to get access to the vm that is running the swefreq website. And also to get an explanation of how it's setup.

Might be relatable to PR #613

**Comment by andkaha** [comment]
There appears to have been an update made to the SweGen data set during this year:
```
swefreq=> select d.short_name, dv.dataset_version from datasets d join dataset_versions dv on (d.id = dv.dataset) order by d.short_name,dv.dataset_version;
 short_name | dataset_version
------------+-----------------
 ACpop      | 20190207
 SweGen     | 20161223
 SweGen     | 20170823
 SweGen     | 20171025
 SweGen     | 20180409
 SweGen     | 20240627
(6 rows)
```

(Note `20240627`.)

It's unclear who did this and how.

**Comment by andkaha** [comment]
The browser's coverage is available for the previous version of the SweGen dataset ("20180409").  See, e.g.,

* https://swefreq.nbis.se/dataset/SweGen/version/20180409/browser/gene/ENSG00000169174

The coverage data is _not_ available for earlier dataset versions.

This leads me to believe that either

* The coverage data associated with the 2024 does genuinely not (and should not) exist, or
* The coverage data does exist, but it was not loaded or loaded in some wrong way, or
* The coverage data should be re-associated with the 2024 data (disassociated from the 2018 data).

**Comment by andkaha** [comment]
The coverage data has been re-associated with the correct version of the SweGen annotations.
